spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.1.6:3306/dreaderserver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:h9R98yyD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:192.168.1.6}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 5000ms
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Shanghai
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 2
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
token:
  header: "Authorization"
  expireTime: 10080
  secret: "I@g2hUQi7Eqk68v&Ft0sMMVdV8xfZ&uwPSvR"
file:
  upload: "/files/"
  meta: "metaData.json"
server:
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 200MB
  port: 8081
minio:
  url: ${MINIO_URL:localhost}
  bucket: ${MINIO_BUCKET:dreader}
  access: ${MINIO_ACCESS:admin}
  secret: ${MINIO_SECRET:admin123}
management:
  health:
    db:
      enabled: false
    redis:
      enabled: false